name: Dependencies

on:
  schedule:
    - cron: "0 16 * * 5" # UTC+8 00:00
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25.0"

      - name: Update dependencies to latest commits
        run: |
          go mod tidy
          go get -u

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "pkg: Update dependencies"
          title: "pkg: Update dependencies"
          branch: deps
          delete-branch: true
